export const SELECT_FILE = 'SELECT_FILE';
export const SET_FILES = 'SET_FILES';
export const RETURN_FILE = 'RETURN_FILE';

export const SET_UPLOAD = 'SET_UPLOAD';
export const HASHING_PROGRESS = 'HASHING_PROGRESS';
export const UPLOADING_PROGRESS = 'UPLOADING_PROGRESS';
export const FILE_UPLOADED = 'FILE_UPLOADED';
export const UPLOAD_DONE = 'UPLOAD_DONE';
export const UPLOAD_ERROR = 'UPLOAD_ERROR';
export const SET_CURRENT_FILE = 'SET_CURRENT_FILE';
export const DOWNLOAD_START = 'DOWNLOAD_START';
export const DOWNLOAD_DONE = 'DOWNLOAD_DONE';
export const DOWNLOAD_PROGRESS = 'DOWNLOAD_PROGRESS';
